### Ex.1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np

n = 10
x = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

##### Расчет с использованием intercept:

In [2]:
B1_1 = (np.mean(x * y) - (np.mean(x) * np.mean(y))) / (np.mean(x**2) - np.mean(x) ** 2)
B1_1

2.620538882402765

In [3]:
A1 = np.mean(y) - B1_1 * np.mean(x)
A1

444.1773573243596

Расчет с использованием матричного метода:

In [4]:
x1 = x.reshape(len(x), 1)
y1 = y.reshape(len(y), 1)
X1 = np.hstack([np.ones((10,1)), x1])

In [5]:
B1_1_1 = np.dot(np.linalg.inv(np.dot(X1.T,X1)),X1.T@y1)
B1_1_1

array([[444.17735732],
       [  2.62053888]])

In [6]:
B1_1_2 = np.linalg.pinv(X1).dot(y1)
B1_1_2

array([[444.17735732],
       [  2.62053888]])

In [7]:
y_hat1 = A1 + (B1_1 * x)
y_hat1

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

In [8]:
mse1 = np.mean((y - y_hat1) ** 2)
mse1

6470.414201176658

##### Расчет без использования intercept:

In [9]:
B1_2 = np.mean(y) / np.mean(x)
B1_2

7.000986193293885

In [10]:
y_hat2 = B1_2 * x
y_hat2

array([ 245.03451677,  315.0443787 , 1330.18737673, 1400.19723866,
        280.03944773,  490.06903353,  378.05325444, 1050.14792899,
        840.1183432 ,  770.10848126])

Расчет с использованием матричного метода:

In [11]:
x2 = x.reshape(len(x), 1)
y2 = y.reshape(len(y), 1)
B1_2_1 = np.dot(np.linalg.inv(np.dot(x2.T,x2)),x2.T@y2)
B1_2_1

array([[5.88982042]])

In [12]:
B1_2_2 = np.linalg.pinv(x2).dot(y2)
B1_2_2

array([[5.88982042]])

In [13]:
mse2 = np.mean((y - y_hat2) ** 2)
mse2

73526.6800654739

In [14]:
import pandas as pd

df = pd.DataFrame({'x': x, 'y': y, 'y_hat1': y_hat1, 'y_hat2': y_hat2}, columns=['x', 'y', 'y_hat1', 'y_hat2'])
df

x    y      y_hat1       y_hat2
0   35  401  535.896218   245.034517
1   45  574  562.101607   315.044379
2  190  874  942.079745  1330.187377
3  200  919  968.285134  1400.197239
4   40  459  548.998913   280.039448
5   70  739  627.615079   490.069034
6   54  653  585.686457   378.053254
7  150  902  837.258190  1050.147929
8  120  746  758.642023   840.118343
9  110  832  732.436634   770.108481

### Ex.2

В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента?

При неизвестной сигме/дисперсии генеральной совокупности используется критерий Стьюдента (таблица критических точек распределения Стьюдента).

Если сигма/дисперсия генеральной совокупности известна, используется Z-критерий (таблица значений функции Лапласа).